[2023-02-16T07:34:14.445+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first_dag_v3.3.task_2 manual__2023-02-16T07:34:11.851713+00:00 [queued]>
[2023-02-16T07:34:14.451+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first_dag_v3.3.task_2 manual__2023-02-16T07:34:11.851713+00:00 [queued]>
[2023-02-16T07:34:14.451+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-16T07:34:14.452+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-16T07:34:14.452+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-16T07:34:14.473+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task_2> on 2023-02-16 07:34:11.851713+00:00
[2023-02-16T07:34:14.479+0000] {standard_task_runner.py:55} INFO - Started process 31867 to run task
[2023-02-16T07:34:14.485+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v3.3', 'task_2', 'manual__2023-02-16T07:34:11.851713+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/dag-1.py', '--cfg-path', '/tmp/tmp2nlayv7j']
[2023-02-16T07:34:14.488+0000] {standard_task_runner.py:83} INFO - Job 141: Subtask task_2
[2023-02-16T07:34:14.565+0000] {task_command.py:388} INFO - Running <TaskInstance: first_dag_v3.3.task_2 manual__2023-02-16T07:34:11.851713+00:00 [running]> on host 20eb5e5814e6
[2023-02-16T07:34:14.629+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tlysenko
AIRFLOW_CTX_DAG_ID=first_dag_v3.3
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T07:34:11.851713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T07:34:11.851713+00:00
[2023-02-16T07:34:14.630+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-16T07:34:14.631+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "It is the second task that follows task_1"']
[2023-02-16T07:34:14.642+0000] {subprocess.py:86} INFO - Output:
[2023-02-16T07:34:14.644+0000] {subprocess.py:93} INFO - It is the second task that follows task_1
[2023-02-16T07:34:14.645+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-02-16T07:34:14.672+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=first_dag_v3.3, task_id=task_2, execution_date=20230216T073411, start_date=20230216T073414, end_date=20230216T073414
[2023-02-16T07:34:14.736+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-16T07:34:14.749+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
